name: Our Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      ## git pull current branch
      - uses: actions/checkout@v3
      - run: ls -al
      - run: cat .github/workflows/checkout.yml
