name: Our Workflow
on:
  push:
    branches:
      - main
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy FrontServer
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_NAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          script: |
            cd ~/web23_MoMyeon/frontend
            git pull
            touch .env
            echo ${{secrets.ENV_CONTENT}} >> .env
            yarn install
            yarn build
            pm2 delete front-server
            pm2 --name 'front-server' start yarn -- start
